# GET http://localhost:23450/plants?keyword=sam
GET http://localhost:23450/plants/1?lat=-7.28589&lon=112.781
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
GET http://localhost:23450/locations/plants?lat=-7.28589&lon=112.781
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
POST http://localhost:23450/auth/login
Content-Type: application/json

{
    "email":"ivan@gmail.com",
    "password":"passs"
}
###
POST http://localhost:23450/auth/register
Content-Type: application/json

{
    "name":"heykam",
    "email":"heykam@gmail.com",
    "password":"heykam"
}

###
GET http://localhost:23450/logout

###
http://localhost:23450/locations/plants?lat=-7.28589&lon=112.781
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
POST http://localhost:8501/v1/models/img_classifier:predict
Content-Type: application/json

{
    "signature_name": "serving_default", 
    "instances": ""
}
###
POST http://localhost:23450/locations/plants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0
Content-Type: application/json

{
    "lat":"-7.3112",
    "lon":"112.791",
    "description":"lokasi random",
    "plant_id":"4"
}
###







POST http://localhost:23450/plants/predict
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0
Content-Type: multipart/form-data; boundary=---------------------------9051914041544843365972754266

-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="image"; filename="Andong0001.jpeg"
Content-Type: image/jpeg

< ./Andong0001.jpeg
-----------------------------9051914041544843365972754266--