# GET http://localhost:3000/plants?keyword=sam
GET http://localhost:3000/plants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email":"ivan@gmail.com",
    "password":"pass"
}
###
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name":"kukira",
    "email":"kukira@gmail.com",
    "password":"kukira"
}

###
GET http://localhost:3000/logout