# GET http://localhost:23450/plants?keyword=sam
GET https://herbapedia-umpbwdfpnq-as.a.run.app/plants
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
GET http://localhost:23450/locations/plants/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
POST http://localhost:23450/auth/login
Content-Type: application/json

{
    "email":"ivan@gmail.com",
    "password":"pass"
}
###
POST http://localhost:23450/auth/register
Content-Type: application/json

{
    "name":"kukira",
    "email":"kukira@gmail.com",
    "password":"kukira"
}

###
GET http://localhost:23450/logout

###
http://localhost:23450/locations
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0

###
POST http://localhost:8501/v1/models/img_classifier:predict
Content-Type: application/json

{
    "signature_name": "serving_default", 
    "instances": ""
}

###
POST https://herbapedia-umpbwdfpnq-as.a.run.app/plants/predict
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Iml2YW5AZ21haWwuY29tIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjU0MjgxMTI2fQ.wJdDWjHUbIkzwVkT44XPVnTOdPlpZmx_8P9fLYyMqD0
Content-Type: multipart/form-data; boundary=---------------------------9051914041544843365972754266

-----------------------------9051914041544843365972754266
Content-Disposition: form-data; name="image"; filename="mnist.png"
Content-Type: image/jpeg

< ./mnist.png
-----------------------------9051914041544843365972754266--